### ISSUE TITLE
Typo in model4-4b.stan

### ISSUE THREAD

**Issue by jhaeberl** [MatsuuraKentaro/Bayesian_Statistical_Modeling_with_Stan_R_and_Python#1]
**Line 24 should be:** vector[Np] yp_base = a + b*Xp[1:Np];

**Line 25 should be:** array[Np] real yp = normal_rng(yp_base[1:Np], sigma);

namely replace **N** with **Np**.

**Comment by MatsuuraKentaro** [comment]
Sorry for the inconvenience. Thank you for the report, I have added it to the errata.
